/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package miniTestProjectWithGit.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }

    public static String testMethod (String arg){
        return arg;
    }

}
