/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package miniTestProjectWithGit.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
    @Test void testMethod() {
        assertEquals("TEST", MessageUtils.testMethod("TEST"));
    }
}
